import type { SalesLeadItem, SalesRepItem, SalesManagerStats, SalesAgentStats } from '../types/sales.types';

export const INITIAL_SALES_REPS: SalesRepItem[] = [
  {
    id: 'usr-sales-1',
    name: 'Rajesh Sharma',
    email: 'rajesh.sharma@taxcrm.com',
    activeLeads: 4,
    pitchesCompletedToday: 8,
    dealsClosedToday: 3,
    totalRevenueToday: 594,
    conversionRate: '37.5%',
  },
  {
    id: 'usr-sales-2',
    name: 'Pooja Hegde',
    email: 'pooja.hegde@taxcrm.com',
    activeLeads: 5,
    pitchesCompletedToday: 11,
    dealsClosedToday: 4,
    totalRevenueToday: 792,
    conversionRate: '36.4%',
  },
  {
    id: 'usr-sales-3',
    name: 'Amit Patel',
    email: 'amit.patel@taxcrm.com',
    activeLeads: 3,
    pitchesCompletedToday: 6,
    dealsClosedToday: 2,
    totalRevenueToday: 396,
    conversionRate: '33.3%',
  },
];

export const INITIAL_SALES_LEADS: SalesLeadItem[] = [
  {
    id: 'sl-101',
    applicationId: 'app-arjun-01',
    taxpayerId: 'usr-arjun-varma',
    taxpayerName: 'Arjun Varma',
    taxpayerEmail: 'arjun.varma@gmail.com',
    taxpayerPhone: '+1 (312) 555-0198',
    taxYear: 2025,
    visaType: 'H-1B (Specialty Worker)',
    maritalStatus: 'Married Filing Jointly (MFJ)',
    stateOfResidence: 'Springfield, IL',
    complexity: 'STANDARD',
    currentStage: 'SALES_PITCH_QUEUE',
    grossIncome: 130350,
    federalRefund: 5770,
    stateRefund: 840,
    balanceDue: 0,
    qaAuditorName: 'Kavita Nair',
    qaAuditorRemarks: 'Verified all W-2 Box 1, 2 withholdings and 1099-INT interest income. Standard deduction MFJ applied accurately. 100% compliant and certified for Sales pitch.',
    qaApprovedAt: new Date().toISOString(),
    assignedSalesAgent: {
      id: 'usr-sales-1',
      name: 'Rajesh Sharma',
      email: 'rajesh.sharma@taxcrm.com',
    },
    feeBreakdown: {
      fed1040PrepFee: 149,
      statePrepFee: 49,
      selectedStates: ['IL (Illinois)'],
      fbarFee: 0,
      auditDefenseFee: 29,
      hasAuditDefense: true,
      discountAmount: 0,
      discountCode: '',
      totalServiceFee: 227,
    },
    paymentStatus: 'UNPAID',
    esignStatus: 'NOT_SENT',
    notes: 'High refund potential ($5,770). Interested in state filing + audit protection shield.',
  },
  {
    id: 'sl-102',
    applicationId: 'app-sneha-02',
    taxpayerId: 'usr-sneha-reddy',
    taxpayerName: 'Sneha M. Reddy',
    taxpayerEmail: 'sneha.reddy@fintechlabs.com',
    taxpayerPhone: '+1 (206) 555-0144',
    taxYear: 2025,
    visaType: 'F-1 OPT (STEM Worker)',
    maritalStatus: 'Single',
    stateOfResidence: 'Seattle, WA',
    complexity: 'INVESTMENTS_1099B',
    currentStage: 'QUOTATION_SENT',
    grossIncome: 148500,
    federalRefund: 3240,
    stateRefund: 0,
    balanceDue: 0,
    qaAuditorName: 'Vikram Deshmukh',
    qaAuditorRemarks: 'Schedule D Capital Gains & 1099-B stock sales audited against Robinhood 1099 consolidated slip. Approved for fee pitch.',
    qaApprovedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    assignedSalesAgent: {
      id: 'usr-sales-2',
      name: 'Pooja Hegde',
      email: 'pooja.hegde@taxcrm.com',
    },
    feeBreakdown: {
      fed1040PrepFee: 149,
      statePrepFee: 0,
      selectedStates: [],
      fbarFee: 0,
      auditDefenseFee: 29,
      hasAuditDefense: true,
      discountAmount: 20,
      discountCode: 'EARLYBIRD20',
      totalServiceFee: 158,
    },
    paymentStatus: 'PAYMENT_LINK_SENT',
    esignStatus: 'SENT',
    notes: 'Quotation sent via email. Waiting for client to swipe credit card on Stripe link.',
  },
  {
    id: 'sl-103',
    applicationId: 'app-naveen-03',
    taxpayerId: 'usr-naveen-k',
    taxpayerName: 'Naveen Krishnan',
    taxpayerEmail: 'naveen.k@energygrids.com',
    taxpayerPhone: '+1 (713) 555-0118',
    taxYear: 2025,
    visaType: 'H-1B (Specialty Worker)',
    maritalStatus: 'Married Filing Jointly (MFJ)',
    stateOfResidence: 'Houston, TX',
    complexity: 'FOREIGN_FBAR',
    currentStage: 'PAID_AND_AUTHORIZED',
    grossIncome: 195000,
    federalRefund: 4120,
    stateRefund: 0,
    balanceDue: 0,
    qaAuditorName: 'Kavita Nair',
    qaAuditorRemarks: 'FinCEN Form 114 Foreign Bank Accounts & Form 8938 verified. Zero discrepancies. Approved.',
    qaApprovedAt: new Date(Date.now() - 86400000).toISOString(),
    assignedSalesAgent: {
      id: 'usr-sales-1',
      name: 'Rajesh Sharma',
      email: 'rajesh.sharma@taxcrm.com',
    },
    feeBreakdown: {
      fed1040PrepFee: 149,
      statePrepFee: 0,
      selectedStates: [],
      fbarFee: 99,
      auditDefenseFee: 29,
      hasAuditDefense: true,
      discountAmount: 0,
      discountCode: '',
      totalServiceFee: 277,
    },
    paymentStatus: 'PAID',
    paymentMethod: 'STRIPE_CARD',
    paidAt: new Date(Date.now() - 7200000).toISOString(),
    transactionRef: 'ch_3N8vKxLkdIw5y72J091xZqLm',
    esignStatus: 'SIGNED',
    esignCompletedAt: new Date(Date.now() - 7000000).toISOString(),
    notes: 'Paid $277 via Stripe. Form 8879 E-Signed. Ready for IRS E-Filing transmission!',
  },
  {
    id: 'sl-104',
    applicationId: 'app-swati-04',
    taxpayerId: 'usr-swati-k',
    taxpayerName: 'Swati R. Kulkarni',
    taxpayerEmail: 'swati.kulkarni@insurancecare.net',
    taxpayerPhone: '+1 (860) 555-0191',
    taxYear: 2025,
    visaType: 'H-1B (Specialty Worker)',
    maritalStatus: 'Single',
    stateOfResidence: 'Hartford, CT',
    complexity: 'STANDARD',
    currentStage: 'SALES_PITCHING',
    grossIncome: 112000,
    federalRefund: 2150,
    stateRefund: 310,
    balanceDue: 0,
    qaAuditorName: 'Vikram Deshmukh',
    qaAuditorRemarks: 'Standard W-2 review completed. Certified for sales quotation.',
    qaApprovedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    assignedSalesAgent: {
      id: 'usr-sales-3',
      name: 'Amit Patel',
      email: 'amit.patel@taxcrm.com',
    },
    feeBreakdown: {
      fed1040PrepFee: 149,
      statePrepFee: 49,
      selectedStates: ['CT (Connecticut)'],
      fbarFee: 0,
      auditDefenseFee: 0,
      hasAuditDefense: false,
      discountAmount: 0,
      discountCode: '',
      totalServiceFee: 198,
    },
    paymentStatus: 'UNPAID',
    esignStatus: 'NOT_SENT',
    notes: 'In active discussion on phone. Reviewing state filing fees.',
  },
];

export const INITIAL_MANAGER_STATS: SalesManagerStats = {
  pipelineLeads: 4,
  activePitching: 2,
  pendingPayment: 1,
  closedPaidDeals: 1,
  totalRevenueMTD: 4890,
  avgDealSize: 224,
  conversionRatePct: 42.5,
};

export const INITIAL_AGENT_STATS: SalesAgentStats = {
  assignedLeads: 2,
  pitchInProgress: 1,
  paymentsPending: 0,
  dealsClosedToday: 1,
  myRevenueToday: 277,
  myConversionRate: 50,
};
