import type { MasterTaxpayerRecord, MasterTaxpayerStats } from '../types/master-taxpayers.types';

export const MOCK_MASTER_TAXPAYERS: MasterTaxpayerRecord[] = [
  {
    id: 'TX-10921',
    customerId: 'CUST-8841',
    leadId: 'LD-9921',
    firstName: 'Manoj',
    lastName: 'Verma',
    email: 'manoj.verma@semicon.com',
    phone: '+1 (408) 555-0192',
    ssnMasked: '***-**-5982',
    fullSsn: '987-65-5982',
    visaType: 'L1',
    filingStatus: 'MARRIED_JOINT',
    acquisitionSource: 'BULK_IMPORT',
    batchRef: 'Tech_Corp_L1_Batch_2026_Q2.csv',
    createdAt: '2026-03-12T09:30:00Z',
    updatedAt: '2026-09-21T16:45:00Z',
    lifecycleStatus: 'CONVERTED',
    currentStage: 'IRS_ACCEPTED',
    currentDepartment: 'COMPLETED',
    assignedAgent: {
      id: 'agent-101',
      name: 'Priya Sharma (CPA Lead)',
      role: 'FILE_OP_TEAM_LEAD',
      email: 'priya.sharma@taxcrm.com',
      department: 'File Operator Hub',
    },
    taxYears: [
      {
        year: 2026,
        status: 'IN_PROGRESS',
        formType: 'FORM_1040',
        federalRefund: 4250,
        stateName: 'CA',
        stateRefund: 850,
      },
      {
        year: 2025,
        status: 'COMPLETED',
        formType: 'FORM_1040',
        federalRefund: 3820,
        stateName: 'CA',
        stateRefund: 720,
        filingDate: '2026-04-10',
        irsAckId: 'ACK-2025-CA-998124',
      },
    ],
    priority: 'HIGH',
    estimatedFee: 450,
    feePaid: 450,
    lastActivity: '2 hours ago',
    city: 'San Jose',
    state: 'CA',
    notes: 'Multi-year retained corporate filer. Form 1040 Married Jointly with stock options (RSU/ESPP).',
    timeline: [
      {
        id: 'tl-1',
        timestamp: '2026-03-12 09:30',
        stage: 'RAW_PROSPECT',
        title: 'Bulk Lead Ingested',
        description: 'Uploaded via corporate Tech_Corp_L1 batch. Deduplication cleared.',
        actor: 'Admin System',
        actorRole: 'SYSTEM',
      },
      {
        id: 'tl-2',
        timestamp: '2026-03-14 11:20',
        stage: 'DOC_OUTREACH',
        title: 'Document Intake Completed',
        description: 'Uploaded W-2, 1099-B, Foreign bank disclosures (FBAR).',
        actor: 'Ramesh Patel',
        actorRole: 'DOC_AGENT',
      },
      {
        id: 'tl-3',
        timestamp: '2026-03-20 15:40',
        stage: 'PREP_IN_PROGRESS',
        title: 'Form 1040 Drafted',
        description: 'Prepared multi-state Form 1040 with Schedule D & Form 8949 capital gains.',
        actor: 'Kavita Rao',
        actorRole: 'TAX_PREPARER',
      },
      {
        id: 'tl-4',
        timestamp: '2026-04-02 10:15',
        stage: 'SALES_PITCH',
        title: 'Service Fee Paid ($450)',
        description: 'Taxpayer approved invoice and authorized e-filing.',
        actor: 'Vikram Singh',
        actorRole: 'SALES_CLOSER',
      },
      {
        id: 'tl-5',
        timestamp: '2026-04-10 17:00',
        stage: 'IRS_ACCEPTED',
        title: 'IRS E-Filing Accepted',
        description: 'Federal and CA State returns accepted. IRS Submission ID: IRS-TX-998124.',
        actor: 'Priya Sharma',
        actorRole: 'CPA / E-FILE',
      },
    ],
  },
  {
    id: 'TX-10922',
    leadId: 'LD-9934',
    firstName: 'Aniket',
    lastName: 'Sharma',
    email: 'aniket.sharma@cloudtech.io',
    phone: '+1 (949) 555-0181',
    ssnMasked: '***-**-3118',
    fullSsn: '987-65-3118',
    visaType: 'F1_OPT',
    filingStatus: 'SINGLE',
    acquisitionSource: 'DIRECT_SIGNUP',
    batchRef: 'Self-Signup Public Web Portal',
    createdAt: '2026-09-20T14:15:00Z',
    updatedAt: '2026-09-23T11:30:00Z',
    lifecycleStatus: 'IN_PIPELINE',
    currentStage: 'PREP_IN_PROGRESS',
    currentDepartment: 'PREP_REVIEW',
    assignedAgent: {
      id: 'agent-102',
      name: 'Kavita Rao (Senior Preparer)',
      role: 'TAX_PREPARER',
      email: 'kavita.rao@taxcrm.com',
      department: 'Prep & Review Dept',
    },
    taxYears: [
      {
        year: 2025,
        status: 'IN_PROGRESS',
        formType: 'FORM_1040_NR',
        federalRefund: 1850,
        stateName: 'TX',
      },
    ],
    priority: 'URGENT',
    estimatedFee: 250,
    lastActivity: '45 mins ago',
    city: 'Austin',
    state: 'TX',
    notes: 'Self-registered student on F-1 STEM OPT with India-US Tax Treaty Article 21(2) standard deduction claim.',
    timeline: [
      {
        id: 'tl-201',
        timestamp: '2026-09-20 14:15',
        stage: 'RAW_PROSPECT',
        title: 'Online Self-Registration',
        description: 'Direct web signup submitted from public portal for TY2025.',
        actor: 'Aniket Sharma (Taxpayer)',
        actorRole: 'SELF_USER',
      },
      {
        id: 'tl-202',
        timestamp: '2026-09-21 09:00',
        stage: 'DOC_OUTREACH',
        title: 'Docs Verified & Assigned',
        description: 'Documenter verified I-20, Form 8843, and W-2. Passed to Prep Dept.',
        actor: 'Ramesh Patel',
        actorRole: 'DOC_AGENT',
      },
      {
        id: 'tl-203',
        timestamp: '2026-09-23 11:30',
        stage: 'PREP_IN_PROGRESS',
        title: 'Tax Calculation In Progress',
        description: 'Preparer calculating treaty benefits under 1040-NR.',
        actor: 'Kavita Rao',
        actorRole: 'TAX_PREPARER',
      },
    ],
  },
  {
    id: 'TX-10923',
    leadId: 'LD-8812',
    firstName: 'Sanjay',
    lastName: 'Gupta',
    email: 'sanjay.gupta@enterprise.org',
    phone: '+1 (206) 555-0144',
    ssnMasked: '***-**-9120',
    fullSsn: '987-65-9120',
    visaType: 'H1B',
    filingStatus: 'MARRIED_JOINT',
    acquisitionSource: 'BULK_IMPORT',
    batchRef: 'Amazon_H1B_Leads_Aug2026.csv',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-09-18T18:00:00Z',
    lifecycleStatus: 'IN_PIPELINE',
    currentStage: 'SALES_PITCH',
    currentDepartment: 'SALES',
    assignedAgent: {
      id: 'agent-103',
      name: 'Vikram Singh (Closer)',
      role: 'SALES_CLOSER',
      email: 'vikram.singh@taxcrm.com',
      department: 'Sales Dept',
    },
    taxYears: [
      {
        year: 2025,
        status: 'IN_PROGRESS',
        formType: 'FORM_1040',
        federalRefund: 5400,
        stateName: 'WA',
      },
    ],
    priority: 'HIGH',
    estimatedFee: 380,
    lastActivity: '3 hours ago',
    city: 'Seattle',
    state: 'WA',
    notes: 'Form 1040 finalized with dual W-2s and rental property Schedule E. Fee pitch sent for $380.',
    timeline: [
      {
        id: 'tl-301',
        timestamp: '2026-08-15 10:00',
        stage: 'RAW_PROSPECT',
        title: 'Bulk Lead Ingested',
        description: 'Ingested from Seattle Amazon H1B batch.',
        actor: 'Admin System',
        actorRole: 'SYSTEM',
      },
      {
        id: 'tl-302',
        timestamp: '2026-08-28 14:00',
        stage: 'DOC_COLLECTION',
        title: 'Documents Completed',
        description: 'W-2s, 1098 Mortgage Interest statement, and Rental expense sheet received.',
        actor: 'Amitabh Sen',
        actorRole: 'DOC_AGENT',
      },
      {
        id: 'tl-303',
        timestamp: '2026-09-12 16:30',
        stage: 'QA_REVIEW',
        title: 'QA Review Approved',
        description: 'Tax Reviewer approved $5,400 refund draft. Ready for sales closer.',
        actor: 'Sunita Mehra',
        actorRole: 'TAX_REVIEWER',
      },
      {
        id: 'tl-304',
        timestamp: '2026-09-18 18:00',
        stage: 'SALES_PITCH',
        title: 'Quote Sent ($380)',
        description: 'Sent formal quote and invoice via email and SMS.',
        actor: 'Vikram Singh',
        actorRole: 'SALES_CLOSER',
      },
    ],
  },
  {
    id: 'TX-10924',
    leadId: 'LD-7719',
    firstName: 'Harish',
    lastName: 'Kapse',
    email: 'harish.kapse@consulting.com',
    phone: '+1 (312) 555-0163',
    ssnMasked: '***-**-7718',
    fullSsn: '987-65-7718',
    visaType: 'H1B',
    filingStatus: 'SINGLE',
    acquisitionSource: 'BULK_IMPORT',
    batchRef: 'Chicago_Consulting_H1B_Batch.csv',
    createdAt: '2026-07-10T12:00:00Z',
    updatedAt: '2026-08-05T09:20:00Z',
    lifecycleStatus: 'DROPPED',
    currentStage: 'DROPPED_PRICING',
    currentDepartment: 'ARCHIVED',
    dropReason: 'Taxpayer requested $150 discount; opted to file via TurboTax Deluxe.',
    taxYears: [
      {
        year: 2025,
        status: 'DROPPED',
        formType: 'FORM_1040',
        federalRefund: 2100,
        stateName: 'IL',
      },
    ],
    priority: 'LOW',
    estimatedFee: 320,
    feePaid: 0,
    lastActivity: '1 month ago',
    city: 'Chicago',
    state: 'IL',
    notes: 'Dropped lead during sales closing. Customer decided fee was too high for single W-2.',
    timeline: [
      {
        id: 'tl-401',
        timestamp: '2026-07-10 12:00',
        stage: 'RAW_PROSPECT',
        title: 'Bulk Lead Ingested',
        description: 'Uploaded via Chicago consulting leads.',
        actor: 'Admin System',
        actorRole: 'SYSTEM',
      },
      {
        id: 'tl-402',
        timestamp: '2026-07-18 11:00',
        stage: 'PREP_IN_PROGRESS',
        title: 'Tax Calculation Prepared',
        description: 'Single W-2 prepared with Illinois state return.',
        actor: 'Kavita Rao',
        actorRole: 'TAX_PREPARER',
      },
      {
        id: 'tl-403',
        timestamp: '2026-08-05 09:20',
        stage: 'DROPPED_PRICING',
        title: 'Lead Dropped - Pricing Dispute',
        description: 'Customer refused $320 quote and closed inquiry.',
        actor: 'Vikram Singh',
        actorRole: 'SALES_CLOSER',
      },
    ],
  },
  {
    id: 'TX-10925',
    leadId: 'LD-9945',
    firstName: 'Deepak',
    lastName: 'Patel',
    email: 'deepak.patel@fintech.net',
    phone: '+1 (212) 555-0155',
    ssnMasked: '***-**-4421',
    fullSsn: '987-65-4421',
    visaType: 'GREEN_CARD',
    filingStatus: 'MARRIED_JOINT',
    acquisitionSource: 'DIRECT_SIGNUP',
    batchRef: 'Self-Signup Public Web Portal',
    createdAt: '2026-09-22T08:00:00Z',
    updatedAt: '2026-09-23T14:10:00Z',
    lifecycleStatus: 'IN_PIPELINE',
    currentStage: 'DOC_COLLECTION',
    currentDepartment: 'DOCUMENTER',
    assignedAgent: {
      id: 'agent-104',
      name: 'Ramesh Patel (Intake Lead)',
      role: 'DOC_AGENT',
      email: 'ramesh.patel@taxcrm.com',
      department: 'Documenter Dept',
    },
    taxYears: [
      {
        year: 2025,
        status: 'IN_PROGRESS',
        formType: 'FORM_1040',
      },
    ],
    priority: 'HIGH',
    estimatedFee: 400,
    lastActivity: '1 hour ago',
    city: 'New York',
    state: 'NY',
    notes: 'Direct web signup. High net worth green card holder with 1099-DIV, K-1 partnership, and multi-state NY/NJ returns.',
    timeline: [
      {
        id: 'tl-501',
        timestamp: '2026-09-22 08:00',
        stage: 'RAW_PROSPECT',
        title: 'Self-Registered Online',
        description: 'Taxpayer registered through public portal.',
        actor: 'Deepak Patel',
        actorRole: 'SELF_USER',
      },
      {
        id: 'tl-502',
        timestamp: '2026-09-23 14:10',
        stage: 'DOC_COLLECTION',
        title: 'Awaiting Schedule K-1',
        description: 'Documenter requested missing Partnership Schedule K-1 for 2025.',
        actor: 'Ramesh Patel',
        actorRole: 'DOC_AGENT',
      },
    ],
  },
  {
    id: 'TX-10926',
    leadId: 'LD-6631',
    firstName: 'Rahul',
    lastName: 'Choudhary',
    email: 'rahul.choudhary@megacorp.com',
    phone: '+1 (469) 555-0177',
    ssnMasked: '***-**-6119',
    fullSsn: '987-65-6119',
    visaType: 'H1B',
    filingStatus: 'SINGLE',
    acquisitionSource: 'BULK_IMPORT',
    batchRef: 'Dallas_H1B_Batch_Jul2026.csv',
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-08-10T12:00:00Z',
    lifecycleStatus: 'DROPPED',
    currentStage: 'DROPPED_UNRESPONSIVE',
    currentDepartment: 'ARCHIVED',
    dropReason: 'Taxpayer unresponsive after 4 automated emails and 2 SMS reminders.',
    taxYears: [
      {
        year: 2025,
        status: 'DROPPED',
        formType: 'FORM_1040',
      },
    ],
    priority: 'LOW',
    estimatedFee: 280,
    feePaid: 0,
    lastActivity: '6 weeks ago',
    city: 'Dallas',
    state: 'TX',
    notes: 'Cold lead dropped after documenter outreach was ignored.',
    timeline: [
      {
        id: 'tl-601',
        timestamp: '2026-07-01 10:00',
        stage: 'RAW_PROSPECT',
        title: 'Bulk Lead Ingested',
        description: 'Ingested from Dallas corporate batch.',
        actor: 'Admin System',
        actorRole: 'SYSTEM',
      },
      {
        id: 'tl-602',
        timestamp: '2026-07-15 15:00',
        stage: 'DOC_OUTREACH',
        title: 'Document Outreach Sent',
        description: 'Follow-ups sent on Day 1, 3, and 7 without response.',
        actor: 'Amitabh Sen',
        actorRole: 'DOC_AGENT',
      },
      {
        id: 'tl-603',
        timestamp: '2026-08-10 12:00',
        stage: 'DROPPED_UNRESPONSIVE',
        title: 'Moved to Dropped Pool',
        description: 'Marked as unresponsive cold lead.',
        actor: 'System Automation',
        actorRole: 'SYSTEM',
      },
    ],
  },
  {
    id: 'TX-10927',
    customerId: 'CUST-7729',
    leadId: 'LD-5510',
    firstName: 'Arjun',
    lastName: 'Varma',
    email: 'arjun.varma@agriglobal.com',
    phone: '+1 (678) 555-0133',
    ssnMasked: '***-**-8822',
    fullSsn: '987-65-8822',
    visaType: 'US_CITIZEN',
    filingStatus: 'MARRIED_JOINT',
    acquisitionSource: 'REFERRAL',
    batchRef: 'Client Referral Program (Ref: CUST-8841)',
    createdAt: '2026-02-10T11:00:00Z',
    updatedAt: '2026-09-15T15:30:00Z',
    lifecycleStatus: 'CONVERTED',
    currentStage: 'IRS_ACCEPTED',
    currentDepartment: 'COMPLETED',
    assignedAgent: {
      id: 'agent-101',
      name: 'Priya Sharma (CPA Lead)',
      role: 'FILE_OP_TEAM_LEAD',
      email: 'priya.sharma@taxcrm.com',
      department: 'File Operator Hub',
    },
    taxYears: [
      {
        year: 2025,
        status: 'COMPLETED',
        formType: 'FORM_1040',
        federalRefund: 6850,
        stateName: 'GA',
        stateRefund: 1200,
        filingDate: '2026-03-28',
        irsAckId: 'ACK-2025-GA-112093',
      },
      {
        year: 2024,
        status: 'COMPLETED',
        formType: 'FORM_1040',
        federalRefund: 5900,
        stateName: 'GA',
        stateRefund: 950,
        filingDate: '2025-04-12',
        irsAckId: 'ACK-2024-GA-882104',
      },
    ],
    priority: 'HIGH',
    estimatedFee: 520,
    feePaid: 520,
    lastActivity: '3 days ago',
    city: 'Atlanta',
    state: 'GA',
    notes: 'High-value multi-year client with small business Form 1120-S schedule and Form 1040.',
    timeline: [
      {
        id: 'tl-701',
        timestamp: '2026-02-10 11:00',
        stage: 'RAW_PROSPECT',
        title: 'Referral Ingested',
        description: 'Referred by Manoj Verma (CUST-8841).',
        actor: 'Admin System',
        actorRole: 'SYSTEM',
      },
      {
        id: 'tl-702',
        timestamp: '2026-03-28 14:20',
        stage: 'IRS_ACCEPTED',
        title: 'Form 1040 E-Filed & Accepted',
        description: 'Federal Refund $6,850 + GA State $1,200 accepted.',
        actor: 'Priya Sharma',
        actorRole: 'CPA / E-FILE',
      },
    ],
  },
  {
    id: 'TX-10928',
    leadId: 'LD-9951',
    firstName: 'Sneha',
    lastName: 'Reddy',
    email: 'sneha.reddy@biotech.org',
    phone: '+1 (617) 555-0199',
    ssnMasked: '***-**-1554',
    fullSsn: '987-65-1554',
    visaType: 'H1B',
    filingStatus: 'SINGLE',
    acquisitionSource: 'DIRECT_SIGNUP',
    batchRef: 'Self-Signup Public Web Portal',
    createdAt: '2026-09-23T09:10:00Z',
    updatedAt: '2026-09-23T16:00:00Z',
    lifecycleStatus: 'IN_PIPELINE',
    currentStage: 'FILING_READY',
    currentDepartment: 'FILE_OPERATOR',
    assignedAgent: {
      id: 'agent-101',
      name: 'Priya Sharma (CPA Lead)',
      role: 'FILE_OP_TEAM_LEAD',
      email: 'priya.sharma@taxcrm.com',
      department: 'File Operator Hub',
    },
    taxYears: [
      {
        year: 2025,
        status: 'IN_PROGRESS',
        formType: 'FORM_1040',
        federalRefund: 3400,
        stateName: 'MA',
        stateRefund: 480,
      },
    ],
    priority: 'URGENT',
    estimatedFee: 310,
    feePaid: 310,
    lastActivity: '15 mins ago',
    city: 'Boston',
    state: 'MA',
    notes: 'Direct online signup. Form 8879 e-signed with 5-digit PIN. Queued for immediate IRS transmission.',
    timeline: [
      {
        id: 'tl-801',
        timestamp: '2026-09-23 09:10',
        stage: 'RAW_PROSPECT',
        title: 'Direct Sign-up Submitted',
        description: 'Submitted online form for TY2025.',
        actor: 'Sneha Reddy',
        actorRole: 'SELF_USER',
      },
      {
        id: 'tl-802',
        timestamp: '2026-09-23 15:30',
        stage: 'PAYMENT_PENDING',
        title: 'Fee Paid & Form 8879 Signed',
        description: 'Invoice paid via Stripe. Form 8879 verified.',
        actor: 'Sneha Reddy',
        actorRole: 'SELF_USER',
      },
      {
        id: 'tl-803',
        timestamp: '2026-09-23 16:00',
        stage: 'FILING_READY',
        title: 'Queued for CPA E-File',
        description: 'Ready in CPA batch transmit queue.',
        actor: 'Priya Sharma',
        actorRole: 'CPA / E-FILE',
      },
    ],
  },
  {
    id: 'TX-10929',
    leadId: 'LD-9952',
    firstName: 'Vikramaditya',
    lastName: 'Rao',
    email: 'vikram.rao@finserve.com',
    phone: '+1 (704) 555-0122',
    ssnMasked: '***-**-9011',
    fullSsn: '987-65-9011',
    visaType: 'L1',
    filingStatus: 'MARRIED_JOINT',
    acquisitionSource: 'BULK_IMPORT',
    batchRef: 'Charlotte_Banking_Leads_2026.csv',
    createdAt: '2026-09-01T14:00:00Z',
    updatedAt: '2026-09-22T10:00:00Z',
    lifecycleStatus: 'STALLED',
    currentStage: 'QA_REVIEW',
    currentDepartment: 'PREP_REVIEW',
    assignedAgent: {
      id: 'agent-105',
      name: 'Sunita Mehra (QA Reviewer)',
      role: 'TAX_REVIEWER',
      email: 'sunita.mehra@taxcrm.com',
      department: 'Prep & Review Dept',
    },
    taxYears: [
      {
        year: 2025,
        status: 'IN_PROGRESS',
        formType: 'FORM_1040',
        federalRefund: 4100,
        stateName: 'NC',
      },
    ],
    priority: 'MEDIUM',
    estimatedFee: 360,
    lastActivity: '1 day ago',
    city: 'Charlotte',
    state: 'NC',
    notes: 'QA Review flagged discrepancy between W-2 box 1 and payroll year-to-date summary. Awaiting reviewer resolution.',
    timeline: [
      {
        id: 'tl-901',
        timestamp: '2026-09-01 14:00',
        stage: 'RAW_PROSPECT',
        title: 'Bulk Lead Ingested',
        description: 'Ingested from Charlotte banking leads.',
        actor: 'Admin System',
        actorRole: 'SYSTEM',
      },
      {
        id: 'tl-902',
        timestamp: '2026-09-22 10:00',
        stage: 'QA_REVIEW',
        title: 'Audit Discrepancy Flagged',
        description: 'Reviewer paused return pending clarification on NC state tax withholding.',
        actor: 'Sunita Mehra',
        actorRole: 'TAX_REVIEWER',
      },
    ],
  },
  {
    id: 'TX-10930',
    leadId: 'LD-9953',
    firstName: 'Pooja',
    lastName: 'Nair',
    email: 'pooja.nair@healthsystems.org',
    phone: '+1 (415) 555-0188',
    ssnMasked: '***-**-2309',
    fullSsn: '987-65-2309',
    visaType: 'B1_B2',
    filingStatus: 'SINGLE',
    acquisitionSource: 'MANUAL_ENTRY',
    batchRef: 'Admin Desk Walk-in / Inbound Call',
    createdAt: '2026-08-20T11:00:00Z',
    updatedAt: '2026-08-25T14:00:00Z',
    lifecycleStatus: 'DROPPED',
    currentStage: 'DROPPED_SELF_FILED',
    currentDepartment: 'ARCHIVED',
    dropReason: 'Taxpayer determined not required to file US returns for 2025 due to B-1/B-2 days of presence test.',
    taxYears: [
      {
        year: 2025,
        status: 'DROPPED',
        formType: 'FORM_1040_NR',
      },
    ],
    priority: 'LOW',
    estimatedFee: 180,
    lastActivity: '3 weeks ago',
    city: 'San Francisco',
    state: 'CA',
    notes: 'Substantial presence test calculated 0 US tax liability; advised no filing needed.',
    timeline: [
      {
        id: 'tl-1001',
        timestamp: '2026-08-20 11:00',
        stage: 'RAW_PROSPECT',
        title: 'Manual Ingest by Admin',
        description: 'Created via admin phone inquiry.',
        actor: 'Admin User',
        actorRole: 'ADMIN',
      },
      {
        id: 'tl-1002',
        timestamp: '2026-08-25 14:00',
        stage: 'DROPPED_SELF_FILED',
        title: 'Closed - No Filing Required',
        description: 'Determined non-resident with zero US source income.',
        actor: 'Ramesh Patel',
        actorRole: 'DOC_AGENT',
      },
    ],
  },
  {
    id: 'TX-10931',
    leadId: 'LD-9954',
    firstName: 'Karthik',
    lastName: 'Subramanian',
    email: 'karthik.sub@autotech.com',
    phone: '+1 (248) 555-0149',
    ssnMasked: '***-**-7190',
    fullSsn: '987-65-7190',
    visaType: 'H1B',
    filingStatus: 'MARRIED_JOINT',
    acquisitionSource: 'BULK_IMPORT',
    batchRef: 'Detroit_Auto_Engineers_2026.csv',
    createdAt: '2026-09-10T16:00:00Z',
    updatedAt: '2026-09-23T17:00:00Z',
    lifecycleStatus: 'IN_PIPELINE',
    currentStage: 'E_FILED',
    currentDepartment: 'FILE_OPERATOR',
    assignedAgent: {
      id: 'agent-101',
      name: 'Priya Sharma (CPA Lead)',
      role: 'FILE_OP_TEAM_LEAD',
      email: 'priya.sharma@taxcrm.com',
      department: 'File Operator Hub',
    },
    taxYears: [
      {
        year: 2025,
        status: 'IN_PROGRESS',
        formType: 'FORM_1040',
        federalRefund: 4900,
        stateName: 'MI',
        stateRefund: 620,
        filingDate: '2026-09-23',
        irsAckId: 'PENDING_ACK_MI_7719',
      },
    ],
    priority: 'URGENT',
    estimatedFee: 375,
    feePaid: 375,
    lastActivity: '10 mins ago',
    city: 'Detroit',
    state: 'MI',
    notes: 'Transmitted to IRS modern e-file gateway. Waiting for electronic acknowledgment confirmation.',
    timeline: [
      {
        id: 'tl-1101',
        timestamp: '2026-09-10 16:00',
        stage: 'RAW_PROSPECT',
        title: 'Bulk Lead Ingested',
        description: 'Ingested from Detroit Auto engineers batch.',
        actor: 'Admin System',
        actorRole: 'SYSTEM',
      },
      {
        id: 'tl-1102',
        timestamp: '2026-09-23 17:00',
        stage: 'E_FILED',
        title: 'Transmitted to IRS',
        description: 'Form 1040 + Form 8879 batch transmitted to IRS MeF system.',
        actor: 'Priya Sharma',
        actorRole: 'CPA / E-FILE',
      },
    ],
  },
  {
    id: 'TX-10932',
    leadId: 'LD-9955',
    firstName: 'Divya',
    lastName: 'Sundaram',
    email: 'divya.sundaram@pharma.org',
    phone: '+1 (609) 555-0164',
    ssnMasked: '***-**-5432',
    fullSsn: '987-65-5432',
    visaType: 'F1_OPT',
    filingStatus: 'SINGLE',
    acquisitionSource: 'DIRECT_SIGNUP',
    batchRef: 'Self-Signup Public Web Portal',
    createdAt: '2026-09-23T13:00:00Z',
    updatedAt: '2026-09-23T15:00:00Z',
    lifecycleStatus: 'IN_PIPELINE',
    currentStage: 'DOC_OUTREACH',
    currentDepartment: 'DOCUMENTER',
    assignedAgent: {
      id: 'agent-104',
      name: 'Ramesh Patel (Intake Lead)',
      role: 'DOC_AGENT',
      email: 'ramesh.patel@taxcrm.com',
      department: 'Documenter Dept',
    },
    taxYears: [
      {
        year: 2025,
        status: 'IN_PROGRESS',
        formType: 'FORM_1040_NR',
      },
    ],
    priority: 'HIGH',
    estimatedFee: 260,
    lastActivity: '30 mins ago',
    city: 'Princeton',
    state: 'NJ',
    notes: 'Direct signup from Princeton University student. Form 8843 and W-2 intake checklist link emailed.',
    timeline: [
      {
        id: 'tl-1201',
        timestamp: '2026-09-23 13:00',
        stage: 'RAW_PROSPECT',
        title: 'Direct Sign-up Ingested',
        description: 'Taxpayer registered online for TY2025.',
        actor: 'Divya Sundaram',
        actorRole: 'SELF_USER',
      },
      {
        id: 'tl-1202',
        timestamp: '2026-09-23 15:00',
        stage: 'DOC_OUTREACH',
        title: 'Intake Checklist Sent',
        description: 'Automated document request email and upload portal link sent.',
        actor: 'Ramesh Patel',
        actorRole: 'DOC_AGENT',
      },
    ],
  },
];

export const calculateMasterStats = (records: MasterTaxpayerRecord[]): MasterTaxpayerStats => {
  const totalRecords = records.length;
  let totalConverted = 0;
  let totalInPipeline = 0;
  let totalDroppedOrStalled = 0;
  let totalDirectSignups = 0;
  let totalBulkIngested = 0;
  let totalManualOrReferral = 0;

  const stageCounts: Record<string, number> = {};
  const departmentCounts: Record<string, number> = {};

  records.forEach((r) => {
    // Lifecycle status
    if (r.lifecycleStatus === 'CONVERTED') totalConverted++;
    else if (r.lifecycleStatus === 'IN_PIPELINE') totalInPipeline++;
    else if (r.lifecycleStatus === 'DROPPED' || r.lifecycleStatus === 'STALLED' || r.lifecycleStatus === 'RETURNED') totalDroppedOrStalled++;

    // Acquisition source
    if (r.acquisitionSource === 'DIRECT_SIGNUP') totalDirectSignups++;
    else if (r.acquisitionSource === 'BULK_IMPORT') totalBulkIngested++;
    else totalManualOrReferral++;

    // Stage counts
    stageCounts[r.currentStage] = (stageCounts[r.currentStage] || 0) + 1;

    // Dept counts
    departmentCounts[r.currentDepartment] = (departmentCounts[r.currentDepartment] || 0) + 1;
  });

  const conversionRate = totalRecords > 0 ? Math.round((totalConverted / totalRecords) * 100) : 0;

  return {
    totalRecords,
    totalConverted,
    totalInPipeline,
    totalDroppedOrStalled,
    totalDirectSignups,
    totalBulkIngested,
    totalManualOrReferral,
    conversionRate,
    stageCounts,
    departmentCounts,
  };
};
