export interface SidebarItemDefinition {
  id: string;
  legacyId?: string;
  label: string;
  department: 'ADMIN' | 'DOC' | 'PREP_REVIEW' | 'SALES' | 'FILE_OP';
  departmentLabel: string;
  path: string;
  section: string;
  description: string;
}

export const MASTER_SIDEBAR_CATALOG: SidebarItemDefinition[] = [
  // 1. Administration (/admin/*)
  {
    id: 'admin_dashboard',
    legacyId: 'dashboard',
    label: 'Dashboard',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/dashboard',
    section: 'Overview',
    description: 'System-wide high-level metrics, conversion rates, and revenue KPI overview.',
  },
  {
    id: 'admin_prospects',
    legacyId: 'prospects',
    label: 'Bulk Lead Import',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/prospects',
    section: 'Intake Pipeline',
    description: 'Bulk CSV imported raw leads awaiting assignment to Documenter calling queues.',
  },
  {
    id: 'admin_self_signups',
    legacyId: 'self-signups',
    label: 'Direct Sign-ups',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/self-signups',
    section: 'Intake Pipeline',
    description: 'Taxpayers who initiated individual filings directly via the self-service web portal.',
  },
  {
    id: 'admin_returned_leads',
    legacyId: 'returned-leads',
    label: 'Returned Leads',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/returned-leads',
    section: 'Intake Pipeline',
    description: 'Leads returned from preparation or sales requiring outreach re-assignment.',
  },
  {
    id: 'admin_all_taxpayers',
    legacyId: 'all-taxpayers',
    label: 'Data',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/all-taxpayers',
    section: 'Directories',
    description: 'Global master index of every contact in the CRM across all stages.',
  },
  {
    id: 'admin_coupons',
    legacyId: 'coupons',
    label: 'Discount Coupons',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/coupons',
    section: 'Commercial',
    description: 'Manage promotion codes, referral discounts, dollar cuts, and percentage offers.',
  },
  {
    id: 'admin_products',
    legacyId: 'products',
    label: 'Products & Services',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/products',
    section: 'Commercial',
    description: 'Manage filing pricing packages and add-on tax filing service products.',
  },
  {
    id: 'admin_customers',
    legacyId: 'customers',
    label: 'Files',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/customers',
    section: 'Directories',
    description: 'Directory of converted taxpayers who have active tax returns and documents.',
  },
  {
    id: 'admin_employees',
    legacyId: 'employees',
    label: 'Team & Staff',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/employees',
    section: 'Access & Team',
    description: 'Employee directory, active status management, capacity tracking, and role allocation.',
  },
  {
    id: 'admin_roles',
    legacyId: 'roles',
    label: 'Roles & Permissions',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/roles',
    section: 'Access & Team',
    description: 'Define custom organizational roles and configure visible sidebar navigation items.',
  },
  {
    id: 'admin_email_templates',
    legacyId: 'email-templates',
    label: 'Email Templates',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/email-templates',
    section: 'Commercial',
    description: 'System communication email templates for onboarding, invoices, and handoffs.',
  },
  {
    id: 'admin_documenter',
    legacyId: 'documenter',
    label: 'Documenter Dept',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/documenter',
    section: 'Departments',
    description: 'Admin view of Documenter department operations and queue management.',
  },
  {
    id: 'admin_prep_review',
    legacyId: 'prep-review',
    label: 'Prep & Review Dept',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/prep-review',
    section: 'Departments',
    description: 'Admin view of Tax Preparation & Review operations and QA audits.',
  },
  {
    id: 'admin_sales',
    legacyId: 'sales',
    label: 'Sales Dept',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/sales',
    section: 'Departments',
    description: 'Admin view of Sales pipelines, closers, and pricing quote authorizations.',
  },
  {
    id: 'admin_filing',
    legacyId: 'filing',
    label: 'File Operator Hub',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/filing',
    section: 'Departments',
    description: 'Admin view of CPA electronic transmission queue and IRS acknowledgements.',
  },
  {
    id: 'admin_notifications',
    legacyId: 'notifications',
    label: 'Notifications',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/notifications',
    section: 'System',
    description: 'System notifications, broadcast alerts, and compliance updates.',
  },
  {
    id: 'admin_settings',
    legacyId: 'settings',
    label: 'System Settings',
    department: 'ADMIN',
    departmentLabel: 'Administration',
    path: '/admin/settings',
    section: 'System',
    description: 'General system configuration, branding, and notification settings.',
  },

  // 2. Documenter Department (/documenter/*)
  {
    id: 'doc_manager_dashboard',
    legacyId: 'dashboard',
    label: 'Operations Dashboard',
    department: 'DOC',
    departmentLabel: 'Documenter Dept',
    path: '/documenter/manager',
    section: 'Management',
    description: 'Intake metrics, documents verified, and conversion throughput.',
  },
  {
    id: 'doc_self_signups',
    legacyId: 'self_signups',
    label: 'Direct Sign-ups',
    department: 'DOC',
    departmentLabel: 'Documenter Dept',
    path: '/documenter/manager/self-signups',
    section: 'Operations',
    description: 'Self-registered leads allocated to the Documenter department.',
  },
  {
    id: 'doc_department_queue',
    legacyId: 'caseload',
    label: 'Department Queue',
    department: 'DOC',
    departmentLabel: 'Documenter Dept',
    path: '/documenter/manager/queue',
    section: 'Operations',
    description: 'Master pool of document collection and outreach prospects.',
  },
  {
    id: 'doc_scorecards',
    legacyId: 'scorecards',
    label: 'Agent Scorecards',
    department: 'DOC',
    departmentLabel: 'Documenter Dept',
    path: '/documenter/manager/scorecards',
    section: 'Operations',
    description: 'Individual documenter outreach metrics, dials, and verified leads.',
  },
  {
    id: 'doc_manager_notifications',
    legacyId: 'notifications',
    label: 'Notifications',
    department: 'DOC',
    departmentLabel: 'Documenter Dept',
    path: '/documenter/notifications',
    section: 'Management',
    description: 'Urgent callbacks, client uploads, and lead assignment alerts.',
  },
  {
    id: 'doc_agent_dashboard',
    legacyId: 'agent_dashboard',
    label: 'Dashboard',
    department: 'DOC',
    departmentLabel: 'Documenter Dept',
    path: '/documenter/agent',
    section: 'Calling Workspace',
    description: 'Daily calling goals, scheduled callbacks, and pending verifications.',
  },
  {
    id: 'doc_my_calling',
    legacyId: 'agent_queue',
    label: 'My Calling',
    department: 'DOC',
    departmentLabel: 'Documenter Dept',
    path: '/documenter/agent/queue',
    section: 'Calling Workspace',
    description: 'Active calling queue assigned to you for document collection.',
  },
  {
    id: 'doc_scheduled_callbacks',
    legacyId: 'agent_callbacks',
    label: 'Scheduled Callbacks',
    department: 'DOC',
    departmentLabel: 'Documenter Dept',
    path: '/documenter/agent/callbacks',
    section: 'Calling Workspace',
    description: 'Appointments and callbacks requested by taxpayers.',
  },
  {
    id: 'doc_fallback_leads',
    legacyId: 'agent_fallback',
    label: 'Fallback Leads',
    department: 'DOC',
    departmentLabel: 'Documenter Dept',
    path: '/documenter/agent/fallback',
    section: 'Calling Workspace',
    description: 'Fallback leads who requested postponed outreach or missing papers.',
  },
  {
    id: 'doc_my_documents',
    legacyId: 'agent_documents',
    label: 'My Documents',
    department: 'DOC',
    departmentLabel: 'Documenter Dept',
    path: '/documenter/agent/documents',
    section: 'Intake Pipeline',
    description: 'Incoming taxpayer paperwork (W-2, 1099, Passports) awaiting review.',
  },
  {
    id: 'doc_agent_notifications',
    legacyId: 'notifications',
    label: 'Notifications',
    department: 'DOC',
    departmentLabel: 'Documenter Dept',
    path: '/documenter/notifications',
    section: 'Calling Workspace',
    description: 'Documenter alerts and calling queue updates.',
  },

  // 3. Tax Preparation & Review (/prep-review/*)
  {
    id: 'prep_manager_dashboard',
    legacyId: 'dashboard',
    label: 'Operations Dashboard',
    department: 'PREP_REVIEW',
    departmentLabel: 'Tax Prep & Review',
    path: '/prep-review/manager',
    section: 'Management',
    description: 'Manager overview of drafting metrics and QA turnaround times.',
  },
  {
    id: 'prep_department_queue',
    legacyId: 'caseload',
    label: 'Department Queue',
    department: 'PREP_REVIEW',
    departmentLabel: 'Tax Prep & Review',
    path: '/prep-review/manager/queue',
    section: 'Operations',
    description: 'Manager pool of returns ready for tax preparer allocation.',
  },
  {
    id: 'prep_staff',
    legacyId: 'staff',
    label: 'Staff Matrix & Capacity',
    department: 'PREP_REVIEW',
    departmentLabel: 'Tax Prep & Review',
    path: '/prep-review/manager/staff',
    section: 'Operations',
    description: 'Preparer & Reviewer staff bandwidth and drafting capacity.',
  },
  {
    id: 'prep_manager_notifications',
    legacyId: 'notifications',
    label: 'Notifications',
    department: 'PREP_REVIEW',
    departmentLabel: 'Tax Prep & Review',
    path: '/prep-review/notifications',
    section: 'Management',
    description: 'Prep department notifications and stage alerts.',
  },
  {
    id: 'prep_specialist_hub',
    legacyId: 'specialist_hub',
    label: 'My Operations Hub',
    department: 'PREP_REVIEW',
    departmentLabel: 'Tax Prep & Review',
    path: '/prep-review/dashboard',
    section: 'Specialist Workspace',
    description: 'Unified operational dashboard for tax preparers and reviewers.',
  },
  {
    id: 'prep_preparer',
    legacyId: 'preparer',
    label: 'Preparer Workbench',
    department: 'PREP_REVIEW',
    departmentLabel: 'Tax Prep & Review',
    path: '/prep-review/preparer',
    section: 'Active Operations',
    description: 'Form 1040 tax drafting cases actively assigned to you.',
  },
  {
    id: 'prep_reviewer',
    legacyId: 'reviewer',
    label: 'QA Audit Deck',
    department: 'PREP_REVIEW',
    departmentLabel: 'Tax Prep & Review',
    path: '/prep-review/reviewer',
    section: 'Active Operations',
    description: 'Four-eyes compliance review queue for quality assurance and compliance sign-off.',
  },
  {
    id: 'prep_specialist_notifications',
    legacyId: 'notifications',
    label: 'Notifications',
    department: 'PREP_REVIEW',
    departmentLabel: 'Tax Prep & Review',
    path: '/prep-review/notifications',
    section: 'Specialist Workspace',
    description: 'Revision requests, QA approvals, and handoff alerts.',
  },

  // 4. Sales Department (/sales/*)
  {
    id: 'sales_manager_dashboard',
    legacyId: 'dashboard',
    label: 'Operations Dashboard',
    department: 'SALES',
    departmentLabel: 'Sales Dept',
    path: '/sales/manager',
    section: 'Management',
    description: 'Sales volume, closed deals, conversion rates, and revenue pipeline.',
  },
  {
    id: 'sales_department_queue',
    legacyId: 'pipeline',
    label: 'Department Queue',
    department: 'SALES',
    departmentLabel: 'Sales Dept',
    path: '/sales/manager/queue',
    section: 'Operations',
    description: 'Returns with finalized draft estimates ready for pricing quotes.',
  },
  {
    id: 'sales_dual_role',
    legacyId: 'dual_role',
    label: 'Dual Doc + Sales',
    department: 'SALES',
    departmentLabel: 'Sales Dept',
    path: '/sales/manager/dual-role',
    section: 'Operations',
    description: 'Combined intake + pricing sales pitch workflow cases.',
  },
  {
    id: 'sales_team',
    legacyId: 'team',
    label: 'Staff Matrix & Capacity',
    department: 'SALES',
    departmentLabel: 'Sales Dept',
    path: '/sales/manager/team',
    section: 'Operations',
    description: 'Sales closers capacity, active pitches, and quotas.',
  },
  {
    id: 'sales_coupons',
    legacyId: 'coupons',
    label: 'Discount Coupons',
    department: 'SALES',
    departmentLabel: 'Sales Dept',
    path: '/sales/coupons',
    section: 'Management',
    description: 'Sales discount codes and authorized margin discounts.',
  },
  {
    id: 'sales_manager_notifications',
    legacyId: 'notifications',
    label: 'Notifications',
    department: 'SALES',
    departmentLabel: 'Sales Dept',
    path: '/sales/notifications',
    section: 'Management',
    description: 'Sales management alerts and quote approvals.',
  },
  {
    id: 'sales_agent_hub',
    legacyId: 'agent_hub',
    label: 'Closer Hub',
    department: 'SALES',
    departmentLabel: 'Sales Dept',
    path: '/sales/agent',
    section: 'Closer Workspace',
    description: 'Pitching pipeline, closed deals today, and pending authorizations.',
  },
  {
    id: 'sales_pitch_queue',
    legacyId: 'pitch_queue',
    label: 'Outreach Pending',
    department: 'SALES',
    departmentLabel: 'Sales Dept',
    path: '/sales/agent/queue',
    section: 'Active Operations',
    description: 'Returns assigned to you for client pricing negotiation and payment.',
  },
  {
    id: 'sales_agent_notifications',
    legacyId: 'notifications',
    label: 'Notifications',
    department: 'SALES',
    departmentLabel: 'Sales Dept',
    path: '/sales/notifications',
    section: 'Closer Workspace',
    description: 'Client quote acceptances, payments, and sign-offs.',
  },

  // 5. Filing Operations (/filing/*)
  {
    id: 'filing_manager_dashboard',
    legacyId: 'dashboard',
    label: 'Operations Dashboard',
    department: 'FILE_OP',
    departmentLabel: 'Filing Operations',
    path: '/filing/manager',
    section: 'Management',
    description: 'CPA e-filing volumes, batch transmissions, and IRS acknowledgements.',
  },
  {
    id: 'filing_department_queue',
    legacyId: 'queue',
    label: 'Department Queue',
    department: 'FILE_OP',
    departmentLabel: 'Filing Operations',
    path: '/filing/manager/queue',
    section: 'Operations',
    description: 'Fully paid and authorized returns queued for IRS transmission.',
  },
  {
    id: 'filing_team',
    legacyId: 'team',
    label: 'Staff Matrix & Capacity',
    department: 'FILE_OP',
    departmentLabel: 'Filing Operations',
    path: '/filing/manager/staff',
    section: 'Operations',
    description: 'CPA and Filing Operator capacity and batch allocation.',
  },
  {
    id: 'filing_manager_notifications',
    legacyId: 'notifications',
    label: 'Notifications',
    department: 'FILE_OP',
    departmentLabel: 'Filing Operations',
    path: '/filing/notifications',
    section: 'Management',
    description: 'Filing manager alerts and IRS batch notices.',
  },
  {
    id: 'filing_agent_hub',
    legacyId: 'agent_hub',
    label: 'Filing Hub',
    department: 'FILE_OP',
    departmentLabel: 'Filing Operations',
    path: '/filing/agent',
    section: 'Filing Workspace',
    description: 'Specialist hub for generation of Drake XML and IRS submission packages.',
  },
  {
    id: 'filing_transmission_queue',
    legacyId: 'agent_queue',
    label: 'Transmission Queue',
    department: 'FILE_OP',
    departmentLabel: 'Filing Operations',
    path: '/filing/agent/queue',
    section: 'Active Operations',
    description: 'Returns assigned to you for Drake XML generation and IRS e-file submission.',
  },
  {
    id: 'filing_agent_notifications',
    legacyId: 'notifications',
    label: 'Notifications',
    department: 'FILE_OP',
    departmentLabel: 'Filing Operations',
    path: '/filing/notifications',
    section: 'Filing Workspace',
    description: 'IRS reject notices, transmission acceptances, and refund acknowledgements.',
  },
];

export const DEPARTMENT_LABELS: Record<string, string> = {
  ADMIN: 'Administration',
  DOC: 'Documenter Dept',
  PREP_REVIEW: 'Tax Prep & Review',
  SALES: 'Sales Dept',
  FILE_OP: 'Filing Operations',
};

/**
 * Filter an array of navigation items against the allowed sidebar permission keys.
 * If user is root ADMIN or no permissions list is enforced, all items are visible.
 */
export function filterNavItemsByPermissions<T extends { id: string; path?: string }>(
  items: T[],
  allowedPermissions?: string[] | null,
  isRootAdmin: boolean = false
): T[] {
  if (isRootAdmin) return items;
  if (!allowedPermissions || allowedPermissions.length === 0) return items;
  const permSet = new Set(allowedPermissions);
  if (permSet.has('*')) return items;

  return items.filter((item) => {
    // Always preserve notifications in all workspaces
    if (item.id === 'notifications') return true;

    // 1. Direct ID match (e.g. 'preparer' or 'prep_preparer')
    if (permSet.has(item.id)) return true;

    // 2. Exact or path match via master catalog
    if (item.path) {
      const match = MASTER_SIDEBAR_CATALOG.find(
        (cat) =>
          cat.id === item.id ||
          cat.legacyId === item.id ||
          cat.path === item.path
      );
      if (
        match &&
        (permSet.has(match.id) || (match.legacyId && permSet.has(match.legacyId)))
      ) {
        return true;
      }
    }

    return false;
  });
}
