import type { PrepReviewLead, PrepStaffMember, PrepManagerStats } from '../types/prep-review.types';

export const INITIAL_PREP_MANAGER_STATS: PrepManagerStats = {
  totalInPipeline: 28,
  unassignedToPrep: 9,
  underPreparation: 11,
  inQualityReview: 5,
  revisionsPending: 3,
  readyForSales: 18,
  avgPreparationTimeHrs: 3.4,
  firstTimePassRate: 94.2,
};

export const MOCK_PREP_STAFF: PrepStaffMember[] = [
  {
    id: 'EMP-PREP-01',
    name: 'Suresh Raina',
    email: 'suresh.r@taxcrm.com',
    mobile: '+1 (555) 019-2001',
    role: 'PREP_MANAGER',
    roleLabel: 'Tax Prep Manager',
    activeCaseload: 0,
    maxCapacity: 20,
    completedThisMonth: 54,
    avgTurnaroundHours: 2.1,
    accuracyRate: 99.4,
    isAvailable: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SureshRaina',
  },
  {
    id: 'EMP-PREP-02',
    name: 'Anjali Rao',
    email: 'anjali.r@taxcrm.com',
    mobile: '+1 (555) 019-2002',
    role: 'TAX_REVIEWER',
    roleLabel: 'Senior QA Reviewer',
    activeCaseload: 3,
    maxCapacity: 12,
    completedThisMonth: 42,
    avgTurnaroundHours: 1.8,
    accuracyRate: 99.1,
    isAvailable: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AnjaliRao',
  },
  {
    id: 'EMP-PREP-03',
    name: 'Vikram Deshmukh',
    email: 'vikram.d@taxcrm.com',
    mobile: '+1 (555) 019-2003',
    role: 'TAX_REVIEWER',
    roleLabel: 'Compliance & QA Reviewer',
    activeCaseload: 2,
    maxCapacity: 12,
    completedThisMonth: 38,
    avgTurnaroundHours: 2.3,
    accuracyRate: 98.4,
    isAvailable: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=VikramDeshmukh',
  },
  {
    id: 'EMP-PREP-04',
    name: 'Deepak Joshi',
    email: 'deepak.j@taxcrm.com',
    mobile: '+1 (555) 019-2004',
    role: 'TAX_PREPARER',
    roleLabel: 'Senior Tax Preparer',
    activeCaseload: 4,
    maxCapacity: 10,
    completedThisMonth: 47,
    avgTurnaroundHours: 3.1,
    accuracyRate: 96.8,
    isAvailable: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DeepakJoshi',
  },
  {
    id: 'EMP-PREP-05',
    name: 'Kavita Nair',
    email: 'kavita.n@taxcrm.com',
    mobile: '+1 (555) 019-2005',
    role: 'TAX_PREPARER',
    roleLabel: 'Tax Draftsman (FBAR Specialist)',
    activeCaseload: 4,
    maxCapacity: 10,
    completedThisMonth: 39,
    avgTurnaroundHours: 3.5,
    accuracyRate: 97.5,
    isAvailable: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=KavitaNair',
  },
  {
    id: 'EMP-PREP-06',
    name: 'Manoj Bajpai',
    email: 'manoj.b@taxcrm.com',
    mobile: '+1 (555) 019-2006',
    role: 'TAX_PREPARER',
    roleLabel: 'Tax Preparer (W-2 & Multi-State)',
    activeCaseload: 3,
    maxCapacity: 10,
    completedThisMonth: 44,
    avgTurnaroundHours: 3.2,
    accuracyRate: 98.0,
    isAvailable: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ManojBajpai',
  },
];

export const MOCK_PREP_LEADS: PrepReviewLead[] = [
  {
    id: 'PL-001',
    applicationId: 'app-001',
    taxpayerId: 'usr-001',
    taxpayerName: 'Arjun Varma',
    taxpayerEmail: 'arjun.varma@gmail.com',
    taxpayerPhone: '+1 (415) 555-0142',
    taxYear: 2025,
    visaType: 'H-1B (Specialty Worker)',
    maritalStatus: 'Single',
    stateOfResidence: 'Springfield, IL',
    complexity: 'STANDARD',
    currentStage: 'DOC_PREP_COMPLETE',
    assignedDocAgent: {
      id: 'agent-kavya',
      name: 'Kavya Reddy',
      email: 'kavya.r@taxcrm.com',
    },
    assignedPreparer: null,
    assignedReviewer: null,
    documentsCount: 3,
    verifiedDocumentsCount: 3,
    organizerPercent: 100,
    estimatedWages: 145000,
    estimatedRefund: 3420,
    estimatedBalanceDue: 0,
    intakeCompletedAt: 'Today, 02:15 PM',
    lastUpdated: '10 mins ago',
  },
  {
    id: 'PL-002',
    applicationId: 'app-002',
    taxpayerId: 'usr-002',
    taxpayerName: 'Priya Sharma',
    taxpayerEmail: 'priya.s@gmail.com',
    taxpayerPhone: '+1 (408) 555-0199',
    taxYear: 2025,
    visaType: 'H-4 EAD',
    maritalStatus: 'Married Filing Jointly',
    stateOfResidence: 'San Jose, CA',
    complexity: 'INVESTMENTS_1099B',
    currentStage: 'PREP_IN_PROGRESS',
    assignedDocAgent: {
      id: 'agent-kavya',
      name: 'Kavya Reddy',
      email: 'kavya.r@taxcrm.com',
    },
    assignedPreparer: {
      id: 'EMP-PREP-04',
      name: 'Deepak Joshi',
      email: 'deepak.j@taxcrm.com',
    },
    assignedReviewer: {
      id: 'EMP-PREP-02',
      name: 'Anjali Rao',
      email: 'anjali.r@taxcrm.com',
    },
    documentsCount: 6,
    verifiedDocumentsCount: 6,
    organizerPercent: 100,
    estimatedWages: 198000,
    estimatedRefund: 5180,
    estimatedBalanceDue: 0,
    intakeCompletedAt: 'Yesterday, 04:30 PM',
    prepStartedAt: 'Today, 09:30 AM',
    dueByDate: 'Tomorrow, 05:00 PM',
    lastUpdated: '1 hour ago',
  },
  {
    id: 'PL-003',
    applicationId: 'app-003',
    taxpayerId: 'usr-003',
    taxpayerName: 'Rohit Kulkarni',
    taxpayerEmail: 'rohit.k@gmail.com',
    taxpayerPhone: '+1 (206) 555-0177',
    taxYear: 2025,
    visaType: 'L-1A (Intracompany)',
    maritalStatus: 'Married Filing Jointly',
    stateOfResidence: 'Seattle, WA',
    complexity: 'FOREIGN_FBAR',
    currentStage: 'QA_IN_REVIEW',
    assignedDocAgent: {
      id: 'agent-rohan',
      name: 'Rohan Gupta',
      email: 'rohan.g@taxcrm.com',
    },
    assignedPreparer: {
      id: 'EMP-PREP-05',
      name: 'Kavita Nair',
      email: 'kavita.n@taxcrm.com',
    },
    assignedReviewer: {
      id: 'EMP-PREP-03',
      name: 'Vikram Deshmukh',
      email: 'vikram.d@taxcrm.com',
    },
    documentsCount: 8,
    verifiedDocumentsCount: 8,
    organizerPercent: 100,
    estimatedWages: 240000,
    estimatedRefund: 8750,
    estimatedBalanceDue: 0,
    intakeCompletedAt: '2 days ago',
    prepStartedAt: 'Yesterday, 11:00 AM',
    reviewStartedAt: 'Today, 11:45 AM',
    dueByDate: 'Today, 06:00 PM',
    lastUpdated: '25 mins ago',
  },
  {
    id: 'PL-004',
    applicationId: 'app-004',
    taxpayerId: 'usr-004',
    taxpayerName: 'Sneha Patel',
    taxpayerEmail: 'sneha.patel@gmail.com',
    taxpayerPhone: '+1 (732) 555-0134',
    taxYear: 2025,
    visaType: 'F-1 OPT (Student)',
    maritalStatus: 'Single',
    stateOfResidence: 'Edison, NJ',
    complexity: 'MULTI_STATE',
    currentStage: 'QA_REVISION_REQUESTED',
    assignedDocAgent: {
      id: 'agent-kavya',
      name: 'Kavya Reddy',
      email: 'kavya.r@taxcrm.com',
    },
    assignedPreparer: {
      id: 'EMP-PREP-06',
      name: 'Manoj Bajpai',
      email: 'manoj.b@taxcrm.com',
    },
    assignedReviewer: {
      id: 'EMP-PREP-02',
      name: 'Anjali Rao',
      email: 'anjali.r@taxcrm.com',
    },
    documentsCount: 4,
    verifiedDocumentsCount: 4,
    organizerPercent: 88,
    estimatedWages: 92000,
    estimatedRefund: 1820,
    estimatedBalanceDue: 0,
    intakeCompletedAt: 'Yesterday',
    prepStartedAt: 'Yesterday, 02:00 PM',
    reviewStartedAt: 'Today, 10:00 AM',
    dueByDate: 'Today, 04:00 PM',
    lastUpdated: '40 mins ago',
  },
  {
    id: 'PL-005',
    applicationId: 'app-005',
    taxpayerId: 'usr-005',
    taxpayerName: 'Vikram Sethi',
    taxpayerEmail: 'vikram.s@outlook.com',
    taxpayerPhone: '+1 (512) 555-0182',
    taxYear: 2025,
    visaType: 'H-1B (Specialty Worker)',
    maritalStatus: 'Single',
    stateOfResidence: 'Austin, TX',
    complexity: 'INVESTMENTS_1099B',
    currentStage: 'DOC_PREP_COMPLETE',
    assignedDocAgent: {
      id: 'agent-rohan',
      name: 'Rohan Gupta',
      email: 'rohan.g@taxcrm.com',
    },
    assignedPreparer: null,
    assignedReviewer: null,
    documentsCount: 5,
    verifiedDocumentsCount: 5,
    organizerPercent: 100,
    estimatedWages: 168000,
    estimatedRefund: 4120,
    estimatedBalanceDue: 0,
    intakeCompletedAt: 'Today, 01:10 PM',
    lastUpdated: '15 mins ago',
  },
];
